/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;
import java.awt.event.KeyEvent;
import static java.lang.System.err;
import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.Statement;
import java.sql.ResultSet; 
import java.sql.SQLException; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.sql.PreparedStatement;

/**
 *
 * @author Dzikr
 */
public class produk extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public produk() {
        initComponents();
        tampilData();
        loadKodeRak();
    }
    private void loadKodeRak() {
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_uts2", "root", "");
        String sql = "SELECT Kode_Rak FROM trak";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        
        flkode.removeAllItems(); // Bersihkan item sebelum diisi
        while (rs.next()) {
            flkode.addItem(rs.getString("Kode_Rak"));
        }
        
        rs.close();
        pst.close();
        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading Kode Rak: " + e.getMessage());
    }
}
    
    

    private void tampilData() {
    DefaultTableModel model = new DefaultTableModel();  
    model.addColumn("Kode Buku");
    model.addColumn("Kode Rak");
    model.addColumn("Nama Produk");
    model.addColumn("Penerbit");
    model.addColumn("Pengarang");
    model.addColumn("Harga");

    try {
    String sql = "SELECT tprodukbuku.Kode_Buku, trak.Kode_Rak, tprodukbuku.Nama_Produk, " +
                 "tprodukbuku.Penerbit, tprodukbuku.Pengarang, tprodukbuku.Harga " +
                 "FROM tprodukbuku " +
                 "INNER JOIN trak ON tprodukbuku.Kode_Rak = trak.Kode_Rak";
    
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_uts2", "root", "");
    Statement stm = conn.createStatement();
    ResultSet res = stm.executeQuery(sql);

    while (res.next()) {
        model.addRow(new Object[]{
            res.getString("Kode_Buku"),
            res.getString("Kode_Rak"),  
            res.getString("Nama_Produk"),
            res.getString("Penerbit"),
            res.getString("Pengarang"),
            res.getString("Harga")
        });
    }
    Tprod.setModel(model);
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal Menampilkan Data: " + e.getMessage());
}

}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tprod = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        fkodeb = new javax.swing.JTextField();
        fnama = new javax.swing.JTextField();
        fpen = new javax.swing.JTextField();
        fpeng = new javax.swing.JTextField();
        fharga = new javax.swing.JTextField();
        flkode = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        del = new javax.swing.JButton();
        ex = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produk Buku");

        Tprod.setAutoCreateRowSorter(true);
        Tprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tprod.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Tprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TprodMouseClicked(evt);
            }
        });
        Tprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TprodKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tprod);

        jLabel2.setText("Kode Buku");

        fkodeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fkodebActionPerformed(evt);
            }
        });

        fnama.setText(" ");
        fnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamaActionPerformed(evt);
            }
        });

        fpen.setText(" ");

        fpeng.setText(" ");

        fharga.setText(" ");
        fharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fhargaActionPerformed(evt);
            }
        });

        flkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flkodeActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        ex.setText("Exit");

        jLabel3.setText("Penerbit");

        jLabel4.setText("Nama Buku");

        jLabel5.setText("Pengarang");

        jLabel6.setText("Harga");

        jLabel7.setText("Kode Rak");

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(del)
                            .addGap(57, 57, 57)
                            .addComponent(clear)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ex, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fpen)
                                    .addComponent(fnama)
                                    .addComponent(fpeng, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(46, 46, 46)
                                        .addComponent(fharga, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)
                                    .addComponent(flkode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(fkodeb, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fkodeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(fharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fpeng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(del)
                    .addComponent(ex)
                    .addComponent(clear))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamaActionPerformed

    private void fkodebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fkodebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fkodebActionPerformed

    private void flkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flkodeActionPerformed

    private void fhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fhargaActionPerformed

    private void TprodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TprodKeyPressed
 if (evt.getKeyCode()==KeyEvent.VK_ENTER)
           { // begin
            fnama.requestFocus();   //panggil komponen yang akan di tuju
          }  //end if
        // TODO add your handling code here:
    }//GEN-LAST:event_TprodKeyPressed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // Ambil nilai dari inputan
  String kodeBuku = fkodeb.getText().trim();
  String namaBuku = fnama.getText().trim();
  String penerbit = fpen.getText().trim();
  String pengarang = fpeng.getText().trim();
  String hargaStr = fharga.getText().trim(); // Harga masih dalam bentuk String
  String kodeRak = flkode.getSelectedItem().toString().trim();

  // Periksa apakah ada field yang kosong
  if (kodeBuku.isEmpty() || kodeRak.isEmpty() || namaBuku.isEmpty() || 
      penerbit.isEmpty() || pengarang.isEmpty() || hargaStr.isEmpty()) {

      JOptionPane.showMessageDialog(null, "Data harus terisi semua!", "Peringatan", JOptionPane.WARNING_MESSAGE);

  } else if (kodeBuku.length() < 8) { // Periksa apakah Kode Buku kurang dari 8 digit
      JOptionPane.showMessageDialog(null, "Kode Buku harus 8 digit!", "Peringatan", JOptionPane.WARNING_MESSAGE);

  } else {
      try {
          // Cek apakah harga adalah angka
          int harga = Integer.parseInt(hargaStr);

          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_uts2", "root", "");

          String cekSql = "SELECT COUNT(*) FROM tprodukbuku WHERE Kode_Buku = ?";
          PreparedStatement cekPst = conn.prepareStatement(cekSql);
          cekPst.setString(1, kodeBuku);
          ResultSet rs = cekPst.executeQuery();
          rs.next();
          int count = rs.getInt(1);
          rs.close();
          cekPst.close();

          if (count > 0) {
              int konfirmasi = JOptionPane.showConfirmDialog(this, "Data sudah ada. Update?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
              if (konfirmasi == JOptionPane.YES_OPTION) {
                  String updateSql = "UPDATE tprodukbuku SET Nama_Produk=?, Penerbit=?, Pengarang=?, Harga=?, Kode_Rak=? WHERE Kode_Buku=?";
                  PreparedStatement updatePst = conn.prepareStatement(updateSql);
                  updatePst.setString(1, namaBuku);
                  updatePst.setString(2, penerbit);
                  updatePst.setString(3, pengarang);
                  updatePst.setInt(4, harga); // Simpan harga sebagai Integer
                  updatePst.setString(5, kodeRak);
                  updatePst.setString(6, kodeBuku);
                  updatePst.executeUpdate();
                  updatePst.close();
                  JOptionPane.showMessageDialog(this, "Data berhasil diupdate.");
              }
          } else {
              String insertSql = "INSERT INTO tprodukbuku (Kode_Buku, Nama_Produk, Penerbit, Pengarang, Harga, Kode_Rak) VALUES (?, ?, ?, ?, ?, ?)";
              PreparedStatement insertPst = conn.prepareStatement(insertSql);
              insertPst.setString(1, kodeBuku);
              insertPst.setString(2, namaBuku);
              insertPst.setString(3, penerbit);
              insertPst.setString(4, pengarang);
              insertPst.setInt(5, harga); // Simpan harga sebagai Integer
              insertPst.setString(6, kodeRak);
              insertPst.executeUpdate();
              insertPst.close();
              JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");
          }

          conn.close();
          refreshTable(); //

      } catch (NumberFormatException e) {
          JOptionPane.showMessageDialog(null, "Harga harus berupa angka!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
      } catch (SQLException e) {
          JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
      }
  }

    }//GEN-LAST:event_saveActionPerformed

    private void TprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TprodMouseClicked
        int row = Tprod.getSelectedRow(); // Ambil baris yang diklik
        if (row != -1) {
        // Ambil data dari tabel ke form
        fkodeb.setText(Tprod.getValueAt(row, 0).toString()); // Kode Buku
        flkode.setSelectedItem(Tprod.getValueAt(row, 1).toString()); // Kode Rak (Combo Box)
        fnama.setText(Tprod.getValueAt(row, 2).toString()); // Nama Buku
        fpen.setText(Tprod.getValueAt(row, 3).toString()); // Penerbit
        fpeng.setText(Tprod.getValueAt(row, 4).toString()); // Pengarang
        fharga.setText(Tprod.getValueAt(row, 5).toString()); // Harga
    }
    }//GEN-LAST:event_TprodMouseClicked

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        String kodeBuku = fkodeb.getText().trim();

    if (kodeBuku.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    } else {
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menghapus data ini?", 
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_uts2", "root", "");
                System.out.println("Koneksi ke database berhasil."); // Debug koneksi

                // Debug cek kode buku yang dikirim
                System.out.println("Kode Buku yang akan dihapus: " + kodeBuku);

                String deleteSql = "DELETE FROM tprodukbuku WHERE Kode_Buku=?";
                PreparedStatement deletePst = conn.prepareStatement(deleteSql);
                deletePst.setString(1, kodeBuku);
                int rowsDeleted = deletePst.executeUpdate();
                deletePst.close();
                conn.close();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                    refreshTable(); // Perbarui tabel setelah penghapusan
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }
    }
}                                    

    }//GEN-LAST:event_delActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        fkodeb.setText("");
        fnama.setText("");
        fharga.setText("");
        fpen.setText("");
        fpeng.setText("");

        // Hapus seleksi di tabel
        Tprod.clearSelection();
    }//GEN-LAST:event_clearActionPerformed
    
    public void refreshTable() {
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_uts2", "root", "");

        String query = "SELECT tprodukbuku.Kode_Buku, Trak.Kode_Rak, tprodukbuku.Nama_Produk, " +
                       "tprodukbuku.Penerbit, tprodukbuku.Pengarang, tprodukbuku.Harga " +
                       "FROM tprodukbuku " +
                       "JOIN Trak ON tprodukbuku.Kode_Rak = Trak.Kode_Rak"; // JOIN diperbaiki

        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) Tprod.getModel();
        model.setRowCount(0); // Hapus data lama di tabel

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("Kode_Buku"),  // Ambil dari tprodukbuku
                rs.getString("Kode_Rak"),   // Diambil dari tabel Trak
                rs.getString("Nama_Produk"),
                rs.getString("Penerbit"),
                rs.getString("Pengarang"),
                rs.getInt("Harga") // Harga pakai getInt karena INT
            });
        }

        // Tutup koneksi
        rs.close();
        ps.close();
        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new produk().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tprod;
    private javax.swing.JButton clear;
    private javax.swing.JButton del;
    private javax.swing.JButton ex;
    private javax.swing.JTextField fharga;
    private javax.swing.JTextField fkodeb;
    private javax.swing.JComboBox<String> flkode;
    private javax.swing.JTextField fnama;
    private javax.swing.JTextField fpen;
    private javax.swing.JTextField fpeng;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
